Repository mindtastic/user-service, pull requests merged in 2022-05, with the labels that each got.

#4 Feature: Add dev setup
  .gitignore
  README.md
  requirements.txt
Labels: documentation

#10 Feature: Setup MongoDB
  Dockerfile
  README.md
  app/main.py
  requirements.txt
Labels: enhancement

#11 Feature: user setting routes and folder structure
  Dockerfile
  README.md
  user_service/__init__.py
  user_service/app.py
  user_service/database.py
  user_service/main.py
  user_service/models/user_model.py
  user_service/models/user_settings_model.py
  user_service/routes/user_routes.py
  user_service/routes/user_settings_routes.py
  user_service/test/__init__.py
  user_service/test/test_routes.py
Labels: enhancement

#15 Feature: Add user routes
  user_service/app.py
  user_service/database.py
  user_service/models/user_model.py
  user_service/models/user_settings_model.py
  user_service/routes/user_routes.py
  user_service/routes/user_settings_routes.py
  user_service/test/test_users_routes.py
Labels: enhancement

#24 Feature: user-settings endpoint testing
  requirements.txt
  user_service/models/user_settings_model.py
  user_service/routes/user_settings_routes.py
  user_service/test/test_user_settings_routes.py
Labels: enhancement

#26 Fix: Get all users routes
  user_service/test/test_user_routes.py
  user_service/test/test_user_settings_routes.py
Labels: bug

#27 Create projects.yml
  .github/workflows/projects.yml
Labels: enhancement
